# -*- mode: python ; coding: utf-8 -*-

# This file was initially generated by `pyi-makespec --onedir t2wml-server.py`
# and later edited.
# run: pyinstaller --clean --noupx t2wml-server.spec

from PyInstaller.utils.hooks import copy_metadata
import sys
from os import path, getcwd
site_packages = next(p for p in sys.path if 'site-packages' in p)

def copy_package(name):
    return [(path.join(site_packages, name), name)]
block_cipher = None


a = Analysis(['t2wml-server.py'],
             pathex=[getcwd()],
             binaries=[],
             datas=copy_package('distributed'),
             hiddenimports=['pandas','pandas._libs.tslibs.base', 'rltk', 'logging.config', 'cmath'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='t2wml-server',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='t2wml-server')