"""empty message

Revision ID: de9b6b09b81a
Revises: 
Create Date: 2020-03-12 13:19:35.842093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9b6b09b81a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('given_name', sa.String(length=64), nullable=True),
    sa.Column('family_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('picture', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.Column('sparql_endpoint', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('project_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_file_filepath'), 'project_file', ['filepath'], unique=False)
    op.create_table('project_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['project_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki_region_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['project_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yaml_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['project_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yaml_file')
    op.drop_table('wiki_region_file')
    op.drop_table('project_sheet')
    op.drop_index(op.f('ix_project_file_filepath'), table_name='project_file')
    op.drop_table('project_file')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
