"""current_sheet as int

Revision ID: 5fb8b4d938e8
Revises: e0ec8d885ed1
Create Date: 2020-07-01 20:02:12.725368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb8b4d938e8'
down_revision = 'e0ec8d885ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datafile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_sheet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_datafile_current_sheet_data_sheet', type_='foreignkey')
        batch_op.drop_column('current_sheet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datafile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_sheet', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_datafile_current_sheet_data_sheet', 'data_sheet', ['current_sheet'], ['id'])
        batch_op.drop_column('current_sheet_id')

    # ### end Alembic commands ###
