"""wikidataitem

Revision ID: a19320d46380
Revises: 1415c158a8f0
Create Date: 2020-05-25 14:53:00.229323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19320d46380'
down_revision = '1415c158a8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikidata_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wd_id', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikidata_item')
    # ### end Alembic commands ###
