"""add extension field to files

Revision ID: d7445578a4c7
Revises: 1e569861c7b7
Create Date: 2020-07-01 16:19:49.311809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7445578a4c7'
down_revision = '1e569861c7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_file', schema=None) as batch_op:
        batch_op.drop_column('extension')

    # ### end Alembic commands ###
