"""current sheet as fk

Revision ID: e0ec8d885ed1
Revises: d7445578a4c7
Create Date: 2020-07-01 19:50:13.075015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ec8d885ed1'
down_revision = 'd7445578a4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datafile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_sheet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_datafile_current_sheet_data_sheet'), 'data_sheet', ['current_sheet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datafile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_datafile_current_sheet_data_sheet'), type_='foreignkey')
        batch_op.drop_column('current_sheet')

    # ### end Alembic commands ###
