"""add index to cache_id

Revision ID: 0a923cbc1283
Revises: 28a3625f6dd6
Create Date: 2021-05-02 13:27:58.664291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a923cbc1283'
down_revision = '28a3625f6dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wikidata_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wikidata_entity_cache_id'), ['cache_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wikidata_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wikidata_entity_cache_id'))

    # ### end Alembic commands ###
