"""empty message

Revision ID: 1415c158a8f0
Revises: de9b6b09b81a
Create Date: 2020-03-25 12:05:40.904816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1415c158a8f0'
down_revision = 'de9b6b09b81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikidata_property',
    sa.Column('wikidata_property', sa.String(length=64), nullable=False),
    sa.Column('property_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('wikidata_property')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikidata_property')
    # ### end Alembic commands ###
