"""Create initial WikidataEntity table

Revision ID: 28a3625f6dd6
Revises: 
Create Date: 2020-09-23 10:54:11.462881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a3625f6dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikidata_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wd_id', sa.String(length=64), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('P31', sa.String(length=64), nullable=True),
    sa.Column('cache_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wikidata_entity'))
    )
    with op.batch_alter_table('wikidata_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wikidata_entity_wd_id'), ['wd_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wikidata_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wikidata_entity_wd_id'))

    op.drop_table('wikidata_entity')
    # ### end Alembic commands ###
