"""add item file

Revision ID: 30abf9658b69
Revises: d3efd3ce8b2d
Create Date: 2020-07-14 14:22:51.739516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30abf9658b69'
down_revision = 'd3efd3ce8b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['saved_file.id'], name=op.f('fk_itemfile_id_saved_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itemfile'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemfile')
    # ### end Alembic commands ###
