"""add directory property to project

Revision ID: 7e10b0c28c75
Revises: 30abf9658b69
Create Date: 2020-08-03 12:29:16.933544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e10b0c28c75'
down_revision = '30abf9658b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_directory', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('file_directory')

    # ### end Alembic commands ###
