"""add label and description to property

Revision ID: d3efd3ce8b2d
Revises: f397bfd28419
Create Date: 2020-07-14 12:17:48.249713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3efd3ce8b2d'
down_revision = 'f397bfd28419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wikidata_property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wikidata_property', schema=None) as batch_op:
        batch_op.drop_column('label')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
