"""add warn for empty cells to project

Revision ID: ec070aa0e62a
Revises: 7e10b0c28c75
Create Date: 2020-08-19 12:24:36.539226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec070aa0e62a'
down_revision = '7e10b0c28c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warn_for_empty_cells', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('warn_for_empty_cells')

    # ### end Alembic commands ###
